# Portable macOS zsh configuration derived from the MSYS2 Bash setup.

if [[ -x /opt/homebrew/bin/brew ]]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
elif [[ -x /usr/local/bin/brew ]]; then
  eval "$(/usr/local/bin/brew shellenv)"
fi

autoload -Uz compinit colors
compinit
colors

setopt APPEND_HISTORY
setopt HIST_IGNORE_DUPS
setopt SHARE_HISTORY

HISTFILE="$HOME/.zsh_history"
HISTSIZE=50000
SAVEHIST=50000

PROMPT='%F{green}%n@%m%f %F{magenta}macOS%f %F{yellow}%~%f
%# '

alias ll='ls -lah'
alias la='ls -A'
